sudo: required
language: python
services:
- docker
env:
  global:
  - APP_ENV=test
  - DOMAINS=travis.test.aws.cmr1.com
before_install:
- pip install awscli
- docker build -t cmr1/sslr .
script:
- echo $APP_ENV
- echo $DOMAINS
# - aws s3 ls
after_success:
- echo "Deploy"
