sudo: required
language: ruby
services:
- docker
env:
  global:
  - APP_ENV=test
  - DOMAINS=travis.test.aws.cmr1.com
  - secure: AxUya8lskpDgq5tBrdL27b4z1r3Vbq4cUxBjci4DcfiH8HXyhclLTi3BegMuw7ckOpkeVxY3n6v66sY3G0pBuhWE4EmJRl1CQaT7u6kice9R+tU3UIhPu/x8s44r1UCL643P0pE29u8bO8gYE2zUL15BZhyzyyIDFkEpyRYZKnowGEe7AeVUfteZjDb5+ptHzp1Qbk7cnQic65xyFXpZxAPW5cGmg2vwzJSHz5AgptJXi/lyss8V4ktgKOOsSAzByHY94Lnkap4zNIVDxHnLrZliypQZJWmglcYWlxIqdZsecTkSxgmF6ImyMCcxkzWQBb4kifIVirQfMSTgfMshxZT3zvUmskNpRhuq70GR+CNE80KDT4025tR2MRS80pnUDBU/9SVLMQQnA2wajPGyE8EEy8dinZMhHUeSXD+VRvWnTgydY7s9K3QcQIcZd/09ctpJJMo0AKemhTqMgcvb22WOpb8/huvB9Ursk5+NM5gDrLzLiXXSl3PkkEis1W3roTy5yNipu9BxGpN7wNBqL9aFz+ww0Ym/7AHPPYH4UecRfYKBZ3G8e5MrvRpwtTAFRvCQAxiZbxV/SaX5kme3cYUMDxKqKpZTh0/DuwQdNzsNZ0oTA4xuIo+Nlx6k1dJoQh0e0a5ROt5Jh3ZNMeXose3FQTpEEdQv58U4KYTU7Iw=
before_install:
- docker build -t cmr1/sslr .
script:
- echo $APP_ENV
- echo $DOMAINS
- echo $SOMETHING
after_success:
- echo "Deploy"
