sudo: required
language: python
services:
- docker
before_install:
- docker build -t cmr1/sslr .
install:
- docker run -v certs:/etc/dehydrated/certs -e APP_ENV=test -e DOMAINS
  -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY cmr1/sslr
script:
- "./test.sh"
after_success:
- "./deploy.sh"
env:
  global:
  - DOMAINS=travis.test.aws.cmr1.com
  - secure: aJjub+4Tt6aMmvos6FrBbqBVT16mGWk5ZVnGN89N3dE41tq+c7n2Y67xsyQc3Wg/b8ArPO2RH0UlT+9frK7tOWg/3cFaXWne7tuE+cUUUf65lYpcbqZz9KSsbBj1IOwqtfvt9M4pL8XLn3Q+rKbvDkcL0DExvOgae+X5/WSjaerfGDNH6HbTGyrD8tiU6c6L9ftMlnS8d8nFCWCWCNKJ/Nviq4NrLOoLRulbM1cZ+JSQhCttuOtvBjLTFf67Eevelb+XRVDO3IO2avvDSrpP5nZ+bZaPMCqglvDR0eK8EE38xJs+rsA7+rv4zK+a0gvVkCnijxljwAFrlBEXJThaek59MvFqDxK+Y7AvQe8z3b66yjzt39r9e1dOCjKC/uq3cLOlRI/EcQIZiVodxGS2UiqItdG+6B07xpGO9r8DFiHB1ilVyJkvDl7TWxkFppq7HfybsIwmBZv96ifay0DAtrcbTFW+T17ppw4SsbtU0F5ZMl/VeX7BDueZNhZvkZdyWQFInCsrwjfcdMNEcXde6+mDGKcc4kZ11eo/v7toqMyYPuj4kn6UVdpEe6dN1GNNfFFtPL0YgOM4t+88GEkWDlMxEbFZ7w4Qcan3WeJL2EgnjaWOP7hFG+lfvIuoEJndjQofrCeV41oLmCerDahQCuwpZsh3jel9sP9GX7hDcqw=
  - secure: PfrT+/3NClRO5g3D4Nmr1Cr4Ot6WpxtoGRg4YaI+GBmFK7YRE0e5eK3A6wK+RV8O1/67PJACzwRq5HV5E40R3/XORK2CbsNVkV5fHVZWsTGc8tUV2LCiBrFhVTM3VnnsvWKdSLEexW4TX3qwl+iJJVRH9FSzVGcJe2OAQlg/SwyxpwvP5t74cIc4ixwlkXys6b/6OQU6CDSkiG0HozF73oTpOHQlVcMQeK8iqNsADuuw/E5WBtEbWmuN7PqK0qATx15kQ6JjbE+BDQy4R9wSW+Irf73/5DZ/6o7KkfUs+nAHMb9IUxtNmmYwfl1aMarANxr5URGnw02c3IgvowqKtQH3uuNDsSGTmJgzaop/txm0e5FYGOsCs0S1EWgp3wNZXpR9rPHvDltUlhDCr7HuVUVknoaCaKJ3YLj4RvQAbfifvSpGgkux/B4oyq2c7QGpcVOm+dNeNWDEzB5N9kw4y467bK2p+OIio+wSY4boFUlGZKZ+Ve6z4UaiEpvGC/Z8Zx7gzd2c0u7xcKcfkRXw+LDbuVUsl03BNdRurbeFAdM2twxDNfmgOQx5c06VtIg74925NCnXOvCOyOU1FbZ8fjzEMRug+VQvfcDxlHJgp9AMkNsIhLzLcJlBNc/jGvGZoOVES0bLRSyfoS/CKQuUOCkod0bCxav0ML2OJx0FY8o=
notifications:
  slack:
    secure: QIG/0v6Ray0cnC5yWU8If1rxmZzdXngFYWr+xD6zI6EcKKXFIGQPeNSA+b6M+WlkgkBv5WajyZJTU+sBJtU3aOWsWYjwXhUwxyG+JVqNGgCzE78rArpaBzbObzqSPuD3Iae2nE7CA4t3aXKuxvJEf7ZVr0A8G4+CxxTEJXkfPOCABe+9zUEdxbW4IIccIqbCvhBFZ+JCUzc8mrW71xVdWtxb+MZc8mkiTg5lenKJ800hMPbWuFpAY8g80HZv2FS+VxHz0TAvhss5lh/w74LHNt1hSN3g1NJbPoPWowL9A156i83/ZUfSHdJjX6je15R8/sMDiAaOB6N1W2qkzokeBKDAGrod85XnI876592Iae8gAKcL8XKwsRbPQf3EPSPMrhUqWacX5bwn7Ed4UYJlf0fSecXrJVflGdLNOg8LW0akO6A4kzlCCT5E7afkz3Tr4bhgcOyTKOE/0byavDS1cBxStr/oZcvpCZQQSmY2CGOtGwOkbHec3XwD8AzdGS0hAW9W7nEgvI7T3EzLv9VzWw3av6C3rxAguPjWDz5v+0OOKCMlxNj36d9cqQLgu5ROHrTKX0GD4iF57wLNv/RbNzKBs4qTSvcOF4Akfovn7pgY/b2QF4c34tsq8dPPqYYgw9T2g6ux3hBcubhNOa0PJ3ytkV/SHwNKdKr8Zh6x8y8=
