sudo: required
language: python
services:
- docker
env:
  global:
  - APP_ENV=test
  - DOMAINS=travis.test.aws.cmr1.com
  - AWS_DEFAULT_REGION=us-east-1
  - AWS_DEFAULT_OUTPUT=json
  - secure: lB10lebHdOUhqCqks1y+cAKH2HUOje1MWRl4PLE/Nj/VxwBsL0CQ++7m6SMUmIWrPUvKt4dkPFiAztL2gDOFZkqhxbDoKlxTLlV0V3UeHp/+8vzeVoEvMNVbjZLPjtGcNFVSMJ+kvt8sLn7AocLzYbYYKfQTHfBhP6RuasJIk39gADVj0LlI2wUyWcbQOIx9Ji43p4lBpHkvNoH3iqHsAeN8+Y9awhTkmxK6jmJVIbpq/zXMi73uwFkbHesNJ6mmDJxrvygWw4FbQ9Djg3N1Laxk7WW14e1ozZuX7duMUuH2XRn/eWfltAdPnMNc+U9gckV+Zi8bW3yg/UgttfISypvD+j4w1kip+V/9NAhiTakmr43FBUGdFH3y3EcJ8qD64i4GJUCtTohDD5sihq4t/Sq5LNrKORNRjAfzHbiI0UOiwmsyRA6p4zW96AXgACUUrWjYh+PHmWWLMeQT5JH7FTy8ogx77SqR34n/Xw6UMzHQBnTHXTDxlVMe/JXuT/jSE5wXwG9p+xPhI99zjUKkd/5z7fKCymuw7gAeeRv8xRX41SV3dSPluk39t6BFlchwC0FOO0YTvT02RVyOvEtHa7M0eROr3qMezfJ375yh0zrIW0t0IHmLYON7ukLqyflTj79c0OzKPBDzTVZJTtsFvYO6nifCG/fFiiQEJTyWY9Q=
  - secure: L5dcg9bnh+aycrwthLoLytkAnWiD9WdMZ6v+wR6N5FjYnqUijHK3qZc47drewpJA7QAaYWxnyil7WFUHCt6E7S4EKGRow74GAR8BWXjtli73MqpjMFXbzFgHdI++nbZENS3+jiqJUsGVGwS8sXS263aYi2Yz+ODWVgAzpaR2Ou5NlFKQOXAc/OeIEM1Eg5vAT5dTmr4QqWl3YmfdST2pyOAUVvbLRVG8gzk/Afigz4OmdJk17lJZogVrK6FtY6Vfylf1iJtG6LRQv8LA0tEK+qTcdhb0StEYfRDyT7pzyhbR4nLMoLi1/5ZuaB1jBDo4ZMOSS/sPy/CPdwADt2oZsbftEdQwmJMKpKYAn4PAfi3YxvwoLihGFWEqg+88L/SK1hiV+QVwYS78IqYjHUzFwSPpxyDTVLjjvMsF5yQAnsGa1LL0wgk+oPv43T1JTAdQXg30AEGfLaQvT1sgrAC+AYx9bkKleERxOa+ycnyK/Z5qtpzigmuKHNcfqo+1NSdWm9BNvJiOZjKjia36ZQjEzAu2HjMDuc9adOOR6vvJswV28O2suPoFe2hob57rpKZAPHpPyqo6p0HD3Qu897tQpeDRmUbXA5FGfIai9+0gH5FFS5HlQp603MLhhonA8J0XB7qIEXEU3c+mTwQJ0fdxz8r4GnFdGIdtpqF0GeQBwWc=
before_install:
- pip install awscli
- docker build -t cmr1/sslr .
script:
- aws s3 ls
after_success:
- echo "Deploy"
notifications:
  slack:
    secure: u4Xt+tgidM/k6FrjUnkkWtbACLHSyRtkm8qa1/kGIWN09aAQ1rPvMB8YTdEn/6KVkZUF3E33C0PkH2roXK9rQtfHN1J9E7VJLuHEQrhQdmm26jDz7n0Okvr7Iaptt9sZbud77qWA6PYjjROFN/0osYs7KDL2YuodX3yl2dXtBc9ZXk3imPXCq0+G8nmHWbhLV3THSeMOsnRXbWkTirDQFrJHHI9mB1GV7fRu3Mc/RDdLHObPJrHjDyfniRntgV8SXPU2lF+2LNuFHIAirIv1AT53zyz3BWYxcw3iOsboOJ0QUtAuxDqgxUqDFf7ekYGzM75zW2uPyXa5ZtaG7xsgmaT89IHddxqDiapEfIfKentgF4LPZwA3tjg2ZquyCqTcDDp3YK8MuX1BokdTWshIUR5SmOONvuUfnn4oDEXkVBBdC50C2EA8lSRliJfNwJPHyD5KhC+Gt+Fc+ME4VWiuIBoCssuhyPCgt+c+BQZSE5UAau3WXpPYy9PcjhpXtG8dP2mUETiftr0RF7X9TtxCdNNC3iMp8YZcnfPv7IX3JXydzvZ3hEQc+mnnLGSXFIwI0r0BSeSXsqs9RSNVBd44j913cctCVAe6fTcQMed0InkC2kMV8ykWCy2UeT0gFOa3PvTA+BbNSxlcr/CTyfxXIvtj8iVlvtq0xdTtQag4xr4=
